[workspace]
authors = ["Naf3tS <stefandel@gmail.com>"]
channels = ["conda-forge"]
name = "2025-advent-of-code"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.1,<3.15"
ipykernel = ">=7.1.0,<8"
